name: enes_dorukbasi
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.1.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  #UI
  cupertino_icons: ^1.0.2
  responsive_sizer: ^3.2.0
  #DATA
  dio: ^5.3.3
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  sqflite: ^2.3.0
  path: ^1.8.3
  html_unescape: ^2.0.0
  fade_scroll_app_bar: ^0.0.7
  custom_will_pop_scope: ^2.1.1
  image_picker: ^1.0.4
  permission_handler: ^11.0.1
  url_launcher: ^6.1.14
  flutter_slidable: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700